### PR TITLE
project: Add Jonathan Gold to AUTHORS

### PR DESCRIPTION
**Pull request by jonathangold**
#342

### CODE REVIEW

**Comment by purpleidea** [comment]
@jonathangold NACK until you pick a better prefix for this awesome commit :)

**Comment by jonathangold** [comment]
@purpleidea Is project cool?

**Comment by purpleidea** [comment]
@jonathangold It's up to you! You get to be creative as long as it passes the tests ;)

**Comment by purpleidea** [comment]
@jonathangold Before I commit and thus store this in the vast eternity that is git master, are you aware that you seem to have not set your git.config author name variable? It was set in other commits you did.

**Comment by jonathangold** [comment]
@purpleidea Good call. I wiped my local repo at configmgmtcamp. I'll fix it now.

**Comment by purpleidea** [comment]
Merged in cfb8deac568c353fe6545e1e4beb59b02855b010

\o/

**Pull request closed without merging**
