### PR TITLE
legal: Re-license to GPLv3

### PR DESCRIPTION
**Pull request by purpleidea**

### CODE REVIEW

**Comment by purpleidea** [comment]
Enough people have complained, so we're going to try this path for now. I'll try and write up a blog post about the whole "legal" experience at some point, but sadly it's hard to innovate in both tech and licensing simultaneously. Sadly, I prefer to focus on the tech.

**Comment by purpleidea** [comment]
For your approval, please state something along the lines of "I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch." or similar. /cc @roidelapluie @ffrank @joejulian 

Anyone other contributors are encouraged to do so as well.

@jumanjiman @vinzenz @jumanjiman @mildred @tuxmea @ChrisMcKenzie

**Comment by vinzenz** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by joejulian** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by roidelapluie** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by tuxmea** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by mildred** [comment]
I agree to re-license my changes under this license and I'm allowed to do so. I approve this patch.

**Comment by ChrisMcKenzie** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by ffrank** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by purpleidea** [comment]
Thanks everyone for your support. I've got a blog post coming shortly about this.

In the interests of being thorough, even if you have written a small patch, if you're willing to also "officially" re-license, please say so. Something like:

"I agree to re-license my changes under this license, I'm allowed to do so, and I approve this patch."

/cc @jumanjiman @mikefaille @juanluisvaladas @dkliban @taksuyu @daenney @jacksgt @jonathangold @artmello @ismaelpuerto @AdnanLFC @kshlm @NeuralSandwich @ashcrow @TomRitserveldt @berrange @LrsK @gzsierra @juergenhoetzel @MaDumont @AXDOOMER @BinaryTiger @jerith @raphink @czerasz @xsb @roobert

Thanks and sorry for the noise.

**Comment by daenney** [comment]
Mmm, I'd like to understand a bit more about why we'd move from AGPL to GPLv3. The main difference is the "application server provider" loophole that this would introduce which I don't really see as being relevant here? Or do businesses just not want to use AGPL licensed software?

**Comment by purpleidea** [comment]
On Tue, Sep 12, 2017 at 7:02 PM, Daniele Sluijters
<notifications@github.com> wrote:
> Mmm, I'd like to understand a bit more about why we'd move from AGPL to
> GPLv3. The main difference is the "application server provider" loophole
> that this would introduce which I don't really see as being relevant here?
> Or do businesses just not want to use AGPL licensed software?

Agreed. It's not very relevant. However FUD notwithstanding, many
folks (some businesses, some individuals) blindly forbid the AGPL. So
in the interests of sustainability, I've decided to make the change.
I've realized that it's very hard to innovate with both code and
licensing, even if the AGPL wouldn't harm anyone. I'm preparing a long
blog post explaining all this, but I'm happy to chat more about this
either here or in channel.

**Comment by daenney** [comment]
Nope, that's good enough for me. I figured it was something like that.

I agree to re-license my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by purpleidea** [comment]
Thanks @daenney, and thanks for your past contributions! Hopefully we'll see more of you in the future.

**Comment by LrsK** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by berrange** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by juanluisvaladas** [comment]
I agree to re-license my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by NeuralSandwich** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by ismaelpuerto** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

El 13 de septiembre de 2017 0:01:32 CEST, James <notifications@github.com> escribió:
>Thanks everyone for your support. I've got a blog post coming shortly
>about this.
>
>In the interests of being thorough, even if you have written a small
>patch, if you're willing to also "officially" re-license, please say
>so. Something like:
>
>"I agree to re-license my changes under this license, I'm allowed to do
>so, and I approve this patch."
>
>/cc @jumanjiman @mikefaille @juanluisvaladas @dkliban @taksuyu @daenney
>@jacksgt @jonathangold @artmello @ismaelpuerto @AdnanLFC @kshlm
>@NeuralSandwich @ashcrow @TomRitserveldt @berrange @LrsK @gzsierra
>@juergenhoetzel @MaDumont @AXDOOMER @BinaryTiger @jerith @raphink
>@czerasz @xsb @roobert
>
>Thanks and sorry for the noise.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/purpleidea/mgmt/pull/218#issuecomment-328997060

-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by ashcrow** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by dkliban** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by jumanjiman** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by czerasz** [comment]
I agree to re-license my changes under this license, I'm allowed to do so,
and I approve this patch.

**Comment by mikefaille** [comment]
​I agree to re-licenses my changes under this license, I'm allowed to do
so, and I approve this patch. (but, I prefer GPLv3+)

**Comment by roobert** [comment]
I agree to re-license my changes under this license, I'm allowed to do so,
and I approve this patch.

**Comment by juergenhoetzel** [comment]
I agree to re-license my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by xsb** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by purpleidea** [comment]
Thanks everyone. I'm going to merge this now. Even if you wrote a very small patch, it's cleaner if you can still ACK the change here.

**Comment by roidelapluie** [comment]
actually you did not release under GPLv3 but under GPLv3+ (not a problem for me)

**Comment by taksuyu** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by artmello** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by AXDOOMER** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by jonathangold** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by jacksgt** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Comment by kshlm** [comment]
I agree to re-licenses my changes under this license, I'm allowed to do so, and I approve this patch.

**Pull request merged**
