### PR TITLE
Tokens should always have a colon when they are followed by a comment (old)

### PR DESCRIPTION
**Pull request by AXDOOMER**

### CODE REVIEW

**Comment by purpleidea** [comment]
@AXDOOMER This patch is reasonable, and I agree, however it's a little too simple as is. If we're going to do this, can you also add a simple patch to test/test-govet.sh that checks for this? It makes sense that it also check for FIXME and TODO as well.

Thanks!

**Comment by AXDOOMER** [comment]
> simple patch to test/test-govet.sh that checks for this

Yeah sure. That's a good idea.

**Comment by purpleidea** [comment]
On Mon, Oct 10, 2016 at 12:07 AM, Alexandre-Xavier Labonté-Lamoureux
<notifications@github.com> wrote:
>
> simple patch to test/test-govet.sh that checks for this
>
> Yeah sure. That's a good idea.

Do you plan to write this addition to the patch and rebase?

Thanks!

**Comment by AXDOOMER** [comment]
I'm planning to remove this pull request when I am done and do a new pull request including the current changes and the patch to test/test-govet.sh.

**Comment by purpleidea** [comment]
On Mon, Oct 10, 2016 at 9:10 PM, Alexandre-Xavier Labonté-Lamoureux
<notifications@github.com> wrote:
>
> I'm planning to remove this pull request when I am done and do a new pull request including the current changes and the patch to test/test-govet.sh.



You can amend this PR by pushing the new changes to this branch.

**Comment by AXDOOMER** [comment]
I'm syncing GitHub with my online repo and I see my new commits appearing here. Travis CI is checking files that I didn't expect it to check and I see that it's failing.

**Comment by purpleidea** [comment]
@AXDOOMER It will still probably fail on:

>			if _, e := obj.CtxError(context.TODO(), err); e != nil {

which is valid code, so you should probably actually check for // TOKEN:
iow, two slashes, a space, a token, and then the colon.

HTH

**Comment by purpleidea** [comment]
Lastly, when you're finished with your patch, please rebase all of your patches into a single commit. If you don't know how to do this, it's a good learning opportunity and we can help :)

**Comment by AXDOOMER** [comment]
I missed that one too. Thanks! I'll fix it.

**Comment by AXDOOMER** [comment]
> which is valid code, so you should probably actually check for // TOKEN:
> iow, two slashes, a space, a token, and then the colon.

I did it so there can be an unlimited amount of spaces between ```//``` and ```TOKEN```
```
[\/]+[\/]+[ ]*+(FIXME[^:]|TODO[^:]|XXX[^:])
```

I think that's preferable because no space or two spaces would break the check as it wouldn't notice a missing colon if the programmer has forgot his space after the ```//```. 

Checking if the programmer as put his space after his ```//``` can be another thing that could be done, but I don't know if it's too radical to check for these.

**Comment by purpleidea** [comment]
Looks approximately right. Please rebase and squash to master into a single nicely worded commit, and we can merge it I think. :)

**Comment by AXDOOMER** [comment]
It failed, there's still a missing ```:```. I'm fixing it right now.

**Comment by AXDOOMER** [comment]
I'll rebase. If I'm not wrong, the command is ```git rebase -i HEAD~n``` where n is the number of commits to rebase. I can't do it from the GitHub GUI for Windows.

**Comment by purpleidea** [comment]
@AXDOOMER Yes, `git rebase -i` is correct, but make sure you know how to use it because it can erase code if you get it wrong! :)

Test on a copy of the branch if you're not sure.

**Comment by AXDOOMER** [comment]
I cloned my repo somewhere else and then I ran the command ```git rebase -i~6```. It says it was successful, but when I try to pull, it says it's already up-to-date.

**Comment by purpleidea** [comment]
You want to push your rebased branch up to here. You'll need the --force arg to make it overwrite this stuff here.

**Comment by AXDOOMER** [comment]
Did it work?

**Comment by purpleidea** [comment]
nope, you've got a big mess sorry. try again.

**Comment by purpleidea** [comment]
So you should have YOUR git master, be identical to MY git master. The work you're doing should be in a feature branch. This is an important point.

**Comment by AXDOOMER** [comment]
I'll try again tomorrow. I'll just delete my repo, reclone yours, then copy my changes into the newly cloned one and do a single commit before I do a new pull request.

**Comment by purpleidea** [comment]
On Tue, Oct 11, 2016 at 2:43 AM, Alexandre-Xavier Labonté-Lamoureux <
notifications@github.com> wrote:

> I'll try again tomorrow. I'll just delete my repo, reclone yours, then
> copy my changes into the newly cloned one and do a single commit before I
> do a new pull request.
>


Sounds good, however try and do it in a feature branch and learn how
rebasing works :) It's easier to explain in person than on GH. Cheers!

**Comment by AXDOOMER** [comment]
New pull request here: https://github.com/purpleidea/mgmt/pull/79

**Pull request closed without merging**
