### PR TITLE
misc: Incorrect dependency path for dvyukov/go-fuzz

### LINKED ISSUE #601: Incorrect dependency path for dvyukov/go-fuzz
## Versions:

* mgmt version (eg: `mgmt --version`): N/A (haven't built yet)

* operating system/distribution (eg: `uname -a`): Linux computer1 4.12.14-lp151.28.48-default #1 SMP Fri Apr 17 05:38:36 UTC 2020 (18849d1) x86_64 x86_64 x86_64 GNU/Linux

* golang version (eg: `go version`): go version go1.13.11 linux/amd64

## Description:
I'm working on building mgmt and ran across an incorrect dependency path for `go-fuzz`. The organization should be `github.com` instead of `golang.org`.

```patch
diff --git a/misc/make-deps.sh b/misc/make-deps.sh
index b2b7a87..77e8499 100755
--- a/misc/make-deps.sh
+++ b/misc/make-deps.sh
@@ -128,7 +128,7 @@ go get golang.org/x/tools/cmd/stringer                      # for automatic stringer-ing
 go get golang.org/x/lint/golint                                # for `golint`-ing
 go get golang.org/x/tools/cmd/goimports                # for fmt
 go get github.com/tmthrgd/go-bindata/go-bindata        # for compiling in non golang files
-go get golang.org/dvyukov/go-fuzz              # for fuzzing the mcl lang bits
+go get github.com/dvyukov/go-fuzz              # for fuzzing the mcl lang bits
 if env | grep -q -e '^TRAVIS=true$' -e '^JENKINS_URL=' -e '^BUILD_TAG=jenkins'; then
        go get -u gopkg.in/alecthomas/gometalinter.v1 && mv "$(dirname $(command -v gometalinter.v1))/gometalinter.v1" "$(dirname $(command -v gometalinter.v1))/gometalinter" && gometalinter --install        # bonus
 fi
```

### PR DESCRIPTION
**Pull request by NiceGuyIT**
Fix the dependency path for dvyukov/go-fuzz to github.com from golang.org.

Fixes #601

## Tips:

* please read the style guide before submitting your patch:
[docs/style-guide.md](../docs/style-guide.md)

* commit message titles must be in the form:

```topic: Capitalized message with no trailing period```

or:

```topic, topic2: Capitalized message with no trailing period```

* golang code must be formatted according to the standard, please run:

```
make gofmt		# formats the entire project correctly
```

or format a single golang file correctly:

```
gofmt -w yourcode.go
```

* please rebase your patch against current git master:

```
git checkout master
git pull origin master
git checkout your-feature
git rebase master
git push your-remote your-feature
hub pull-request	# or submit with the github web ui
```

* after a patch review, please ping @purpleidea so we know to re-review:

```
# make changes based on reviews...
git add -p		# add new changes
git commit --amend	# combine with existing commit
git push your-remote your-feature -f
# now ping @purpleidea in the github PR since it doesn't notify us automatically
```

### CODE REVIEW

**Comment by purpleidea** [comment]
LGTM, thank you! I'll merge shortly. Cheers and let me know if you'd like to get involved with more patches or have questions about mgmt.

**Comment by nixinator** [comment]
has this been merged in to master? master doesn't reflect this change?

**Comment by purpleidea** [comment]
@nixinator My bad, and thank you @NiceGuyIT -- all merged now. I've been a bad maintainer recently as I was avoiding stashing my WIP hacking, and I've been trying to focus on big blocker to 0.1 issues in mgmt. Thanks again!

**Comment by nixinator** [comment]
these are minor!

however just noticed the change still doesn't work.

go get github.com/dvyukov/go-fuzz
can't load package: package github.com/dvyukov/go-fuzz: no Go files in /home/demo/go/src/github.com/dvyukov/go-fuzz

seems go-fuzz has moved things around upstream.

go get github.com/dvyukov/go-fuzz/go-fuzz

**Comment by purpleidea** [comment]
Fix in master.

**Pull request merged**
