### PR TITLE
add systemd unit file

### PR DESCRIPTION
**Pull request by jumanjiman**
Here is a handful of commits to add a systemd unit file.

Let me know if...

* you'd prefer to drop or break out any of these commits
* any of the commit messages need more explanation

Diff in github gui without whitespace changes: https://github.com/purpleidea/mgmt/pull/26/files?w=1

### CODE REVIEW

**Comment by purpleidea** [comment]
Hi @jumanjiman always a pleasant surprise when patches end up in your inbox. This is virtually "LGTM", except I was hoping you wouldn't mind answering a quick question, and fixing a small nitpick...

RE: https://github.com/purpleidea/mgmt/pull/26/commits/d36cba84f50ed8f3d623bcd02b70245522ddeabe can you provide a bit more background please? Here in the comments is fine, doesn't need to be in the git commit. TBH this is probably due to my lack of understanding in the go build system and what people want to accomplish outside of the normal `go build`.

Nits (either happy to do these myself, to accept as a "misc" patch, or as a rebase) :
* add a trailing slash on https://github.com/purpleidea/mgmt/ text in systemd file.
* remove the line from the TODO file... woo :)

Lastly, mentioning git show -w is a friendly thing to do in a commit message, although i am already aware of the unfortunate git mess gofmt rules make of our commit history. :P

Thanks again for the patches and please let me know if you'd like to work on a feature or another aspect of the code!

**Comment by jumanjiman** [comment]
wrt d36cba8 (now https://github.com/purpleidea/mgmt/pull/26/commits/26543844613f8ee99d341c752e101ba3a7a84311)

Specifically: CoreOS uses glibc, but it does not have a
package manager. It also has a read-only OS (`/usr/`).
Thus I'd like to compile a binary that can be dropped
into CoreOS and have zero dependencies.



> add a trailing slash on https://github.com/purpleidea/mgmt/ text in systemd file.

good catch. done.



> remove the line from the TODO file

done! (i'm originally from texas, so i can't read...hehe)



> mentioning git show -w is a friendly thing to do in a commit message, although i am already aware of the unfortunate git mess gofmt rules make of our commit history.

i know you're aware, but others may not be. i've developed a habit to make such comments at `$dayjob`, and i've been pleasantly surprised by the positive reactions i've received from people just entering the space. 



> let me know if you'd like to work on a feature or another aspect of the code!

absolutely.

currently we use https://github.com/jumanjiman/puppet-on-coreos at dayjob for coreos hosts. however...what if there were a statically-compiled binary (no deps!) that could achieve the same outcomes on *any* linux distro (or windows, too!)? it's an exciting thought!

i've looked through the issues, and there are several things i'd like to work on in my free time (for now). i can't promise any time commitment, but `mgmt` is an exciting approach, and i'd love to help move it forward.

**Comment by purpleidea** [comment]
> i know you're aware, but others may not be. i've developed a habit to make such comments at $dayjob, and i've been pleasantly surprised by the positive reactions i've received from people just entering the space. 

It's the first time I've seen it in a commit, and I have no objections! Very informative, but might get crazy if every commit had it ;)

> currently we use https://github.com/jumanjiman/puppet-on-coreos at dayjob for coreos hosts. however...what if there were a statically-compiled binary (no deps!) that could achieve the same outcomes on any linux distro (or windows, too!)? it's an exciting thought!

Of course it would be lovely to have this self contained management! We're working on it :) As an aside, I'll be speaking at the upcoming CoreOS fest in Berlin in case you happen to be around there.

> i've looked through the issues, and there are several things i'd like to work on in my free time (for now). i can't promise any time commitment, but mgmt is an exciting approach, and i'd love to help move it forward.

Sounds good to me, feel free to hang out in #mgmtconfig IRC on Freenode, and ping me if you'd like to discuss specifics, or would like to talk about ideas I haven't put on the TODO list yet.

Merged! Welcome to the club!

**Comment by jumanjiman** [comment]
> Very informative, but might get crazy if every commit had it ;)

ack



> As an aside, I'll be speaking at the upcoming CoreOS fest in Berlin in case you happen to be around there.

rockstar (:rocket: ⭐ )! i wish i could be there!
if you run into any of my colleagues from Deutsche-Boerse, please say hallo!

(i spoke at tectonic in nyc recently)





> feel free to hang out in #mgmtconfig IRC on Freenode, and ping me if you'd like to discuss specifics, or would like to talk about ideas I haven't put on the TODO list yet.
> 
> Merged! Welcome to the club!

tyvm! ttys!

**Comment by purpleidea** [comment]
>  if you run into any of my colleagues from Deutsche-Boerse, please say hallo!

Sounds good! If they're around and want to hack on some mgmt, have them ping me and I'll find some time to look at their patches or chat about mgmt stuff.

**Comment by jumanjiman** [comment]
i'll alert them 😺

**Comment by purpleidea** [comment]
@jumanjiman On closer inspection, I was thinking your systemd additions to the README might be more useful in the DOCUMENTATION file. What do you think about transplanting it as a new section under reference? https://github.com/purpleidea/mgmt/blob/master/DOCUMENTATION.md#reference

Cheers

**Comment by jumanjiman** [comment]
> What do you think about transplanting it as a new section under reference?

gimme a few minutes to create a new pr

**Comment by purpleidea** [comment]
thanks, and sorry for not thinking about this earlier

**Comment by purpleidea** [comment]
on the +ive side, more commits means more internets points, the idea is to beat @ffrank for more useful commits ;)

**Comment by jumanjiman** [comment]
https://github.com/purpleidea/mgmt/pull/27



> the idea is to beat @ffrank for more useful commits ;)

#winning! 

winning

**Pull request merged**
