### PR TITLE
[WIP] Add github actions support

### PR DESCRIPTION
**Pull request by evrardjp**

### CODE REVIEW

**Comment by evrardjp** [comment]
Rebased on top of PR #622

**Comment by purpleidea** [comment]
Awesome start! I left you comments in the other PR to explain the failure. HTH

And as mentioned I've got a started branch here, so if you can use the rough draft of that, hopefully it helps!

https://github.com/purpleidea/mgmt/tree/feat/gh-testing

**Comment by evrardjp** [comment]
Oh sure, let me abandon this then, and patch yours. Not sure I can rebase it, if any rebase is necessary.

**Comment by purpleidea** [comment]
On Thu, Dec 10, 2020 at 5:03 AM Jean-Philippe Evrard
<notifications@github.com> wrote:
>
> Oh sure, let me abandon this then, and patch yours. Not sure I can rebase it, if any rebase is necessary.

Up to you, and you can just "steal" the code in that one and make a
new patch out of it. Of course the goal is to make something useful
work, so I point it out in case it's helpful concretely or
stylistically.

**Comment by evrardjp** [comment]
> On Thu, Dec 10, 2020 at 5:03 AM Jean-Philippe Evrard ***@***.***> wrote: Oh sure, let me abandon this then, and patch yours. Not sure I can rebase it, if any rebase is necessary.
> Up to you, and you can just "steal" the code in that one and make a new patch out of it. Of course the goal is to make something useful work, so I point it out in case it's helpful concretely or stylistically.

I am no thief! I have seen we have arrived to the same kind of code, so I am attributing that to you in the meantime. Let's see where this PR is heading towards, and if I progress, I will make a clean PR eventually, either this one, or yours. Don't worry I will make sure we can follow things by commenting in the PRs.

**Comment by evrardjp** [comment]
Here is a log listing the files present in the environment: https://pipelines.actions.githubusercontent.com/XW3kdXQsyx2PgvDbJY2noZ5uPN406kTSjCpCgDOTHGza6eVHI7/_apis/pipelines/1/runs/18/signedlogcontent/5?urlExpires=2020-12-14T10%3A34%3A51.3959370Z&urlSigningMethod=HMACV1&urlSignature=bkYtSF0G%2BCMocWvh2r3wXPfqyKHhvKwIhqmFAOOFtbs%3D

As you can see, the `./bindata` folder only contains a Makefile. Interestingly `./lang/funcs/bindata` contains a `doc.go`. Also interesting, the log shows `2020-12-14T09:52:21.5076014Z Generating: bindata...` showing it does go through the generation of bindata, but didn't generate anything. 

Any help is welcomed.

**Comment by purpleidea** [comment]
@evrardjp If you run the root `Makefile` it will call all the nested Makefiles... And you should see this in the logs from a clean build:

```
Generating: bindata...
Generating: native mcl...
Generating: lexer...
Generating: parser...
Generating: type kind strings...
Generating: funcs...
```
(then the binary actually builds)

LMK if you need anything else.

**Comment by evrardjp** [comment]
> @evrardjp If you run the root `Makefile` it will call all the nested Makefiles... And you should see this in the logs from a clean build:
> 
> ```
> Generating: bindata...
> Generating: native mcl...
> Generating: lexer...
> Generating: parser...
> Generating: type kind strings...
> Generating: funcs...
> ```
> 
> (then the binary actually builds)
> 
> LMK if you need anything else.

I don't disagree. On the link I pasted, you can see the line appearing, yet the build failed. But let me dig deeper if what I am following here is not a red herring.

**Comment by purpleidea** [comment]
On Wed, Dec 16, 2020 at 4:15 AM Jean-Philippe Evrard
<notifications@github.com> wrote:
>
> @evrardjp If you run the root Makefile it will call all the nested Makefiles... And you should see this in the logs from a clean build:
>
> Generating: bindata...
> Generating: native mcl...
> Generating: lexer...
> Generating: parser...
> Generating: type kind strings...
> Generating: funcs...
>
> (then the binary actually builds)
>
> LMK if you need anything else.
>
> I don't disagree. On the link I pasted, you can see the line appearing, yet the build failed. But let me dig deeper if what I am following here is not a red herring.

The link "expired". Post fpaste or gist links or something different if you can.

**Comment by evrardjp** [comment]
Oh yeah, next time I will push on a pastebin somewhere. anyway, I will dig deeper first. Thanks for the help.

**Comment by purpleidea** [comment]
On Wed, Dec 16, 2020 at 4:20 AM Jean-Philippe Evrard
<notifications@github.com> wrote:
>
> Oh yeah, next time I will push on a pastebin somewhere. anyway, I will dig deeper first. Thanks for the help.

Anytime! I'm on IRC for next hour or so if you want sync-help.

Cheers

**Comment by frebib** [comment]
I started playing with your PR and added some things. I made a bit of a mess, but in the current state, the tests work at least on Ubuntu. macOS is another story entirely though
https://github.com/frebib/mgmt/commit/ca0891185f033cc4493d231ddbd6957efeace57c

I had to hack a lot in the testing framework so Github did a pretty with the blocks.
No idea if anyone wants to use any of this, but it's there if you want

**Comment by purpleidea** [comment]
@frebib I don't care about mac... Open this as a new PR and let's see if GH runs the tests properly!

**Comment by purpleidea** [comment]
I copied @frebib's commit into a PR at: https://github.com/purpleidea/mgmt/pull/633 to see what GH actions does...

**Comment by purpleidea** [comment]
I think most of this is merged now. If you can take a look and see if there's anything else that needs changing, please do so and open a new PR, issue, or make a comment please =D Thanks

**Pull request closed without merging**
