### PR TITLE
Added --lang to the quick start guide example

### PR DESCRIPTION
**Pull request by laf**
Without it, the examples don't run.

## Tips:

* please read the style guide before submitting your patch:
[docs/style-guide.md](../docs/style-guide.md)

* commit message titles must be in the form:

```topic: Capitalized message with no trailing period```

or:

```topic, topic2: Capitalized message with no trailing period```

* golang code must be formatted according to the standard, please run:

```
make gofmt		# formats the entire project correctly
```

or format a single golang file correctly:

```
gofmt -w yourcode.go
```

* please rebase your patch against current git master:

```
git checkout master
git pull origin master
git checkout your-feature
git rebase master
git push your-remote your-feature
hub pull-request	# or submit with the github web ui
```

* after a patch review, please ping @purpleidea so we know to re-review:

```
# make changes based on reviews...
git add -p		# add new changes
git commit --amend	# combine with existing commit
git push your-remote your-feature -f
# now ping @purpleidea in the github PR since it doesn't notify us automatically
```

### CODE REVIEW

**Comment by purpleidea** [comment]
@laf Thanks for the patch, however `--lang` was removed in the most recent git master (and I think also a released version) so it's no longer there.

I would recommend using a newer version too =D

**Comment by laf** [comment]
Used the latest release from github. 

Thanks for looking at the pr so quick

**Comment by purpleidea** [comment]
@laf You're right. I'm quite sorry, it was changed in https://github.com/purpleidea/mgmt/commit/43839d10904624dae987a28eabbc6e1f12c65ebd and this commit is not yet in a release. I actually recommend `git master` at this point since the project is quite new and we try to keep it stable.

Please let me know if you have any more questions (IRC is best) and let me know if you can contribute either code or donations!

Cheers!

**Comment by laf** [comment]
> @laf You're right. I'm quite sorry, it was changed in [43839d1](https://github.com/purpleidea/mgmt/commit/43839d10904624dae987a28eabbc6e1f12c65ebd) and this commit is not yet in a release. I actually recommend `git master` at this point since the project is quite new and we try to keep it stable.

Don't apologise @purpleidea :)

I'm not actually running it yet, just went through some examples.

**Pull request closed without merging**
