### PR TITLE
makefile: Added strip to binary, to decrease the total bin size

### PR DESCRIPTION
**Pull request by toshywoshy**
makefile: Add strip to binary build

It strips the binary making it about 50% smaller

### CODE REVIEW

**Comment by jonathangold** [comment]
Hi @toshywoshy. fyi, 
> commit message titles must be in the form: topic: Capitalized message with no trailing period or: topic, topic2: Capitalized message with no trailing period

Also, would be nice to have an explanation of what this patch does below that in the commit message. eg:

> makefile: Add strip to binary build
>
>Explanation of what it does and why in sentence form.

Thanks for the patch! :D

**Comment by toshywoshy** [comment]
update

**Comment by jonathangold** [comment]
@toshywoshy Thanks, but you need to change the title of your commit. ie.

> $git commit --amend
> // edit the commit message
> $git push -f

Also, what does it remove that makes it so much smaller?

**Comment by jonathangold** [comment]
@toshywoshy You can re-open the pull request. When you `git push -f` it will update the commit.

**Comment by toshywoshy** [comment]
Replaced by 268

**Pull request closed without merging**
