### PR TITLE
make art : Prefer imagemagik over inkscape

### PR DESCRIPTION
**Pull request by mikefaille**
Since imagemagik is lighter, faster and come without X dependencies.

### CODE REVIEW

**Comment by purpleidea** [comment]
Hi @mikefaille,

Thanks for the patch!

I actually wanted to use imagemagick initially, but for some reason on my system, I couldn't get any command to set the background colour correctly. Can you confirm this works for you? As it does not on my machine pick #ff0000 for red to test for example).

Also the inkscape versions gave better quality output without the need for tweaking.

Thanks!

**Comment by mikefaille** [comment]
I'll check this.

**Comment by mikefaille** [comment]
if I use that command (I test high resolution image too) : 
```
convert -background "#ff0000" -size 4000 art/mgmt_logo_default_tall.svg "art/mgmt_logo_default_tall.png"
```
I get my red background ! https://postimg.org/image/p7qtk44u1/22fde102/
(and, the quality seems right)

> Also the inkscape versions gave better quality output without the need for tweaking.
I don't compare. Actually, with imagemagik, I think we are fine since generated images are small.

**Comment by purpleidea** [comment]
@mikefaille This is completely strange, because that command does _not_ produce the expected red results on my machine:

```
$ convert --version
Version: ImageMagick 6.9.2-7 Q16 x86_64 2015-12-06 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype gslib jbig jng jp2 jpeg lcms ltdl lzma openexr pangocairo png ps rsvg tiff webp wmf x xml zlib
```

I don't know why (probably my fault somehow), and since this isn't a major part of the project, and it isn't a bug, I'm going to respectfully close this without merge, sorry.

Your other three patches LGTM though and I'll merge those shortly.

As an aside: Unless something is blocking your work (I can't see how this particular issue is) work on a core patch instead of these fiddly things, that way I can announce you out to the world as having got some real core shit merged, and it will be cooler than the lesser seen (but still important) things.

If you're not sure about what to work on, LMK on IRC and we can discuss.

Cheers!

**Comment by mikefaille** [comment]
> @mikefaille This is completely strange, because that command does not produce the expected red results on my machine: (...)

For the record, on my side, I got : 
Version: ImageMagick 6.9.5-2 Q16 x86_64 2016-09-06

And, yes, I want change the word ! I just figure out if basic things work for me. Now, I want to dive deeper. :v:

**Comment by purpleidea** [comment]
> I just figure out if basic things work for me. Now, I want to dive deeper.

Sounds very reasonable, I too poke around with fiddly things at first when I encounter new projects.
Looking forward for the more interesting stuff. Cheers!

**Pull request closed without merging**
