### PR TITLE
Fix broken link to graph.yaml section

### PR DESCRIPTION
**Pull request by xsb**

### CODE REVIEW

**Comment by purpleidea** [comment]
@xsb Thanks! Strangely, this fixes the issue in github markdown, but breaks the link when running pandoc... Any idea of how to fix both? The `make docs` target does the pandoc file...

**Comment by xsb** [comment]
@purpleidea What about changing the section title from *graph.yaml* to *Graph definition file*?

**Comment by purpleidea** [comment]
WFM :) Want to update the patch? Thanks

**Comment by xsb** [comment]
Done. I also tested the PDF output after running `make docs` and the link works fine.

**Comment by purpleidea** [comment]
LGTM, thanks!

**Comment by purpleidea** [comment]
@xsb Also, congratulations on your first commit, let's hope it's not the last!

**Pull request merged**
