### PR TITLE
Use GOTAGS for static builds as well

### PR DESCRIPTION
**Pull request by kshlm**

### CODE REVIEW

**Comment by purpleidea** [comment]
@kshlm Patch looks good but failed our commit message CI test:

```
FAIL: Commit message should match the following regex: '^\([a-z0-9]\(\(, \)\|[a-z0-9]\)\+[a-z0-9]: \)\+[A-Z0-9][^:]\+[^:.]$'
```

Basically patch should start with a lowercase prefix like foo: The commit message

Maybe `build: Use GOTAGS...`

**Comment by kshlm** [comment]
@purpleidea Changing the commit message would mean the commit-id, and the commit itself changes. I generally don't like that, but I guess you're okay with that?

**Comment by purpleidea** [comment]
On Mon, Feb 20, 2017 at 9:30 AM, Kaushal M <notifications@github.com> wrote:
>
> @purpleidea Changing the commit message would mean the commit-id, and the commit itself changes. I generally don't like that, but I guess you're okay with that?



Rebasing patches before they're in git master is +1 :)

**Comment by purpleidea** [comment]
@kshlm Have no idea why this is failing now...

@roidelapluie or @ffrank any idea why is it unhappy about libvirt/augeas stuff now?

**Comment by roidelapluie** [comment]
E: Unable to locate package libvirt-dev

Reading package lists... Done

Building dependency tree       

Reading state information... Done

E: Unable to locate package libaugeas-dev

**Comment by purpleidea** [comment]
On Mon, Feb 20, 2017 at 4:05 PM, Julien Pivotto
<notifications@github.com> wrote:
>
> E: Unable to locate package libvirt-dev
>
> Reading package lists... Done
>
> Building dependency tree
>
> Reading state information... Done
>
> E: Unable to locate package libaugeas-dev



Why did this break? It used to work... And what's the fix?

**Comment by roidelapluie** [comment]
Fixed ; you can retrigger the travis jobs

**Comment by purpleidea** [comment]
Merged! Thanks

**Pull request closed without merging**
