### PR TITLE
test: Switch to goimports instead of gofmt

### PR DESCRIPTION
**Pull request by xiu**
see https://github.com/purpleidea/mgmt/pull/256#issuecomment-346360414

### CODE REVIEW

**Comment by purpleidea** [comment]
Patch LGTM, but can you add this change in Makefile as well (gofmt target binary, but leave the name the same) and also add the -s if you want?

**Comment by xiu** [comment]
Updated, goimports doesn't have a -s option though. I can add a run of gofmt -w -s before goimports if you want

**Comment by purpleidea** [comment]
@xiu Actually, I was hoping you'd remove that old comment of mine and add the -s :)
But yeah, we'd need to do it in two runs. I'm okay with that if you'd like to write the patch :) :)

**Comment by xiu** [comment]
Ok, done :) I've just doubled the find command to keep it clear

**Comment by purpleidea** [comment]
Patch LGTM-- the two files that are updated when you run this are simplifications we didn't previously check. You can commit those with this patch as well :)

Thanks!

**Comment by purpleidea** [comment]
(rebased to master and merged)

Thank you!

**Comment by purpleidea** [comment]
ac629404f499a34d71db71b995d79893d5aff565

**Pull request closed without merging**
