### PR TITLE
lang: funcs: Add datetime/hour function

### PR DESCRIPTION
**Pull request by roidelapluie**
Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

## Tips:

* please read the style guide before submitting your patch:
[docs/style-guide.md](../docs/style-guide.md)

* commit message titles must be in the form:

```topic: Capitalized message with no trailing period```

or:

```topic, topic2: Capitalized message with no trailing period```

* golang code must be formatted according to the standard, please run:

```
make gofmt		# formats the entire project correctly
```

or format a single golang file correctly:

```
gofmt -w yourcode.go
```

* please rebase your patch against current git master:

```
git checkout master
git pull origin master
git checkout your-feature
git rebase master
git push your-remote your-feature
hub pull-request	# or submit with the github web ui
```

* after a patch review, please ping @purpleidea so we know to re-review:

```
# make changes based on reviews...
git add -p		# add new changes
git commit --amend	# combine with existing commit
git push your-remote your-feature -f
# now ping @purpleidea in the github PR since it doesn't notify us automatically
```

### CODE REVIEW

**Comment by roidelapluie** [comment]
echo // time. The time is the number of seconds since the epoch, and matches what|wc
      1      15      77


77 < 80 ?

**Comment by purpleidea** [comment]
```
// Hour returns the hour of the day corresponding to the input
// time. The time is the number of seconds since the epoch, and matches what
// comes from our Now function.
```

is not wrapped to 80. Start of second line fits on first line and then reflow the rest too.

**Comment by roidelapluie** [comment]
done

**Comment by purpleidea** [comment]
It's still not wrapped properly... Don't you have a line in your editor??

**Comment by roidelapluie** [comment]
done1

**Comment by purpleidea** [comment]
Merged, thanks! \o/

**Pull request merged**
