### PR TITLE
Changed wording of quick start section. Issue #98.

### PR DESCRIPTION
**Pull request by LrsK**
Issue #98 discusses some wording in the quick start guide. Attempted to make it clearer.

### CODE REVIEW

**Comment by purpleidea** [comment]
@LrsK Awesome, thanks! Could you make two really small changes please:

s/Go/golang/ so it's less ambiguous for new readers, and could you add a "readme: " prefix to your commit message?

Thanks!!

**Comment by LrsK** [comment]
Did that work? :)

**Comment by purpleidea** [comment]
@LrsK The changes are perfect, but this is now two commits instead of one.
You want to rebase these into a single commit. This is good practice if you've never done it before, but I can advise how if you need the help. Please LMK.

**Comment by LrsK** [comment]
I've never done a rebase before, so that was fun to try. I messed up a few times too, so I got to try it several times. ;)

**Comment by purpleidea** [comment]
@LrsK Great! Glad you tried out rebasing! Pro-tip: for simple single patch fixes, when you made the changes I asked for the first time around, instead of doing `git commit` there is a rebase shortcut: `git commit --amend` which will merge the new changes into the last commit. Then you can force push up here.

HTH and thanks for the patch! Send us some more!

**Pull request merged**
