### PR TITLE
[WIP] Add a config file to replace common command line flags

### PR DESCRIPTION
**Pull request by sebastianrakel**
This PR is currently WIP it should add the new feature in the end

I openend this PR so other people can see the development state of this feature

This is realted to #319

### CODE REVIEW

**Comment by purpleidea** [comment]
@sebastianrakel Thanks for the patch! So in general, unless I'm misunderstanding something, this would pin the cli library at an older version, instead of the current git master... Here's an FAQ about this:

https://github.com/purpleidea/mgmt/blob/master/docs/faq.md#why-arent-you-using-glide-or-godep-for-dependency-management

Is there a reason we want to make an exception here?

**Comment by sebastianrakel** [comment]
As i wrote in the commit 

> To add the config option of the cli lib, we need to switch to the
> gopkg.in package, because it's used in the internal development
> of this lib

The altsrc package witch is needed to load a config file, references "gopkg.in/urfave/cli.v1"
like here: https://github.com/urfave/cli/blob/master/altsrc/yaml_file_loader.go

so we have to options, pin our lib to v1 because v2 is unstable and not ready or open a bug upstream to change this behavior

**Comment by purpleidea** [comment]
@sebastianrakel Sorry for my delay in replying. I was a bit buried with recent travel. Back on track now =D

> so we have two options, pin our lib to v1 because v2 is unstable and not ready or open a bug for upstream to change his import statement

Gah, you're right. Thanks for pointing this out. Can you open a bug? Feel free to CC me, and explain that this blocks us from running `git master`. Thanks again.

**Comment by purpleidea** [comment]
@sebastianrakel I don't know if this is an issue anymore. If so please LMK and I'll reopen. If you still want to work on this please lmk! Thanks!

**Pull request closed without merging**
