### PR TITLE
test: Ensure github CI tests commit messages

### PR DESCRIPTION
**Pull request by evrardjp**
Without this patch, the travis var is empty, and we just pass.
This is a problem, as we are using github CI nowadays.

This should fix it.

### CODE REVIEW

**Comment by evrardjp** [comment]
@frebib WDYT?

**Comment by evrardjp** [comment]
Testing done in https://github.com/purpleidea/mgmt/pull/640/

**Comment by purpleidea** [comment]
I like the test you did. But I think:

```
  running ./test/test-commit-message.sh
  fatal: ambiguous argument 'origin/github-ci-commit-messages..13ad047e46dad0c0e2121c06c806107a475fbaa1': unknown revision or path not in the working tree.
  Use '--' to separate paths from revisions, like this:
  'git <command> [<revision>...] -- [<file>...]'
```

**Comment by evrardjp** [comment]
Passing now, the other one is broken, as expected.

**Comment by purpleidea** [comment]
LGTM, thanks!

**Comment by purpleidea** [comment]
@evrardjp I rebased this to master and merged it. Thank you for your excellent and prompt work. Your dedication to helping us keep a high bar with testing is much appreciated.

**Comment by purpleidea** [comment]
I have bad news... I spoke too soon. It's a good patch, but apparently it doesn't like git master: https://github.com/purpleidea/mgmt/runs/2020176385?check_suite_focus=true#step:6:139 :/

**Comment by purpleidea** [comment]
(nobody really knows how git works)

**Pull request closed without merging**
