### PR TITLE
util: Rename SortedStrSliceCompare and move to util package 

### PR DESCRIPTION
**Pull request by jonathangold**

### CODE REVIEW

**Comment by purpleidea** [comment]
@jonathangold ACK, however can you make one small change please: can you move this to the main util package in the root at the same time? I want to use the method elsewhere too. Thanks Also would `SortedStrSliceCompare` be a better name? Up to you.

**Comment by jonathangold** [comment]
@purpleidea Done, and done.

**Comment by purpleidea** [comment]
LGTM :)

**Comment by purpleidea** [comment]
Merged, Thanks!

**Pull request merged**
