### PR TITLE
add new build requirements to README.md

### PR DESCRIPTION
**Pull request by ffrank**

### CODE REVIEW

**Comment by purpleidea** [comment]
So all of these deps are really part of etcd, and they have their deps, and so on, so I'm not sure if it makes sense to always list these. Usually when you run go get ... https://github.com/purpleidea/mgmt/blob/master/misc/make-deps.sh#L41 you get everything automatically.

**Comment by ffrank** [comment]
Until I ran those `go get`s, the compiler would complain that they were missing.

Perhaps I should have gone and update `etcd` instead? Will try that later. Hopefully that *will* fix #55 then.

We need some sort of `bundler` for this mess. In the meantime, could there perhaps be an early build target that just makes sure all library versions are adequate?

**Comment by ffrank** [comment]
No dice. Just started over with a clean `$GOPATH` and want to `go get` all from the README. Results:

```
Building: mgmt.static, version: 0.0.3-61-ga1ed034...
go generate
stringer: checking package: etcd.go:62:7: could not import github.com/coreos/etcd/clientv3 (can't find import: github.com/coreos/etcd/clientv3)
```

After `go get`ting that, same with `etcdserver`, now `cockroachdb cmux`.

Running `go1.5.4` from `gimme`.

**Comment by ffrank** [comment]
FWIW I'm reproducing this with a fresh clone of `mgmt` from github.

I don't really understand why it's failing. This line is in `github.com/coreos/etcd/clientv3/op.go`:

    type OpOption func(*Op)

So that's a declaration, no?

**Comment by purpleidea** [comment]
@ffrank Still don't know why you have this issue, but git master now points to a commit near etcd git master. LMK if you still have issues. Closing this.

**Comment by ffrank** [comment]
`make` gave me this today:

```
stringer: checking package: etcd.go:63:2: could not import github.com/coreos/etcd/embed (can't find import: github.com/coreos/etcd/embed)
```

This was solved by `go get`ting that package, which put the corresponding `.a` file in `$GOPATH/pkg`.

**Comment by purpleidea** [comment]
@ffrank The problem is that you're not *recursively* cloning with git. That is provided by the git repo as a submodule. Either that or you're not using GO15VENDOREXPERIMENT=1 in your environment.

HTH

**Pull request closed without merging**
