### PR TITLE
pgraph: Move the BackPoke to before the semaphores

### PR DESCRIPTION
**Pull request by purpleidea**
I can't think of a reason we should grab a semaphore before backpoking.
The semaphore is intended to block around the actual work in CheckApply,
not the dependency resolution of the correct vertex.

### CODE REVIEW

**Comment by purpleidea** [comment]
@roidelapluie @ffrank or anyone else would like to do a quick review. Cheers!

**Comment by purpleidea** [comment]
Merging due to no comments.

**Comment by roidelapluie** [comment]
Was ok.

**Comment by ffrank** [comment]
I currently lack the insight into the logic flow to make a sensible comment on this kind of change.
You *seem* to have thought it through so :)

**Comment by purpleidea** [comment]
@ffrank I know you might today, but I was trying to get you to want to dive into looking into it in case you were curious. Next time :)

**Pull request closed without merging**
