### PR TITLE
build: add gcc,pkg-config deps

### PR DESCRIPTION
**Pull request by 42wim**
Add gcc and pkg-config dependencies for archlinux

### CODE REVIEW

**Comment by purpleidea** [comment]
This will probably fail since the commit message must start will a capital
Otherwise looks good.

See https://github.com/purpleidea/mgmt/blob/master/test/test-commit-message.sh

**Comment by 42wim** [comment]
Oops sorry

**Comment by purpleidea** [comment]
@42wim 

> Oops sorry

haha, no apologies needed, it's part of the learning process to our CI :) Sorry for the trouble!

**Comment by purpleidea** [comment]
Merged in 3a50171d1974e700ed1358b23b57065f2639b194

Thank you :)

**Pull request closed without merging**
