### PR TITLE
resources: aws: ec2: Close the listener when serve returns

### PR DESCRIPTION
**Pull request by jonathangold**
Moved defer close(awsChan) out of the goroutine, to prevent the server from sending a message on a closed channel during shutdown.

### CODE REVIEW

**Comment by purpleidea** [comment]
Bug fix patches (especially one/two line patches) need long commit messages describing the bug, why this is the fix, etc...

**Comment by jonathangold** [comment]
@purpleidea Let me know if the commit message is informative enough.

**Comment by jonathangold** [comment]
@purpleidea: I fixed the lack of listener.Close(), but still working on the races. Will ping you when it's ready, or I run out of ideas.

**Comment by jonathangold** [comment]
Closing this one, since it doesn't fix the bug. Will open a new pull request when we have it figured out.

**Pull request closed without merging**
