### PR TITLE
examples, fix: Fixed pkg example with cowsay

### PR DESCRIPTION
**Pull request by yohanb**
```
 _______________________________________
/ Please accept my PR. moo              \
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

### CODE REVIEW

**Comment by purpleidea** [comment]
@yohanb 

Can you add the is_debian function (I think it works for ubuntu too?) https://github.com/purpleidea/mgmt/blob/master/lang/funcs/core/os/family_func.go#L43 and use it with the elvis operator :? (see elvis*.mcl example) so that we only add this param on ubuntu? Does it work like that?

Thanks!

**Comment by yohanb** [comment]
> @yohanb
> 
> Can you add the is_debian function (I think it works for ubuntu too?) https://github.com/purpleidea/mgmt/blob/master/lang/funcs/core/os/family_func.go#L43 and use it with the elvis operator :? (see elvis*.mcl example) so that we only add this param on ubuntu? Does it work like that?
> 
> Thanks!

 ___________
< it works! >
 -----------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by purpleidea** [comment]
@yohanb Patches LGTM, thanks!

PS: Can you confirm you tested the is_debian version and that it works??

**Comment by yohanb** [comment]
> @yohanb Patches LGTM, thanks!
> 
> PS: Can you confirm you tested the is_debian version and that it works??

Yes, I tested on Ubuntu 18.04 and it worked.

**Comment by purpleidea** [comment]
Merged, thank you again!

If you'd like to write another patch for us, please LMK!

**Pull request merged**
