### PR TITLE
Add the requested art

### PR DESCRIPTION
**Pull request by bartjanssens92**
Signed-off-by: bjanssens <bjanssens@inuits.eu>

Adding the poohbear meme from twitter in the art directory.

### CODE REVIEW

**Comment by purpleidea** [comment]
@bartjanssens92 Patch will fail with commit error message. Needs an `art: ` prefix please =D

**Comment by purpleidea** [comment]
Fun fact, we actually even have an FAQ about this.

https://github.com/purpleidea/mgmt/blob/master/docs/faq.md#in-mgmt-you-talk-about-events-what-is-this-referring-to

In particular the last paragraph in that entry. =D

**Comment by purpleidea** [comment]
@bartjanssens92 LGTM. FYI: your git `user.name` probably isn't set properly. I can hold off on merge if you'd prefer to set it and re-push.

**Comment by bartjanssens92** [comment]
@purpleidea No that's fine, it sets me apart from all the ppl with the same name :)

**Comment by purpleidea** [comment]
> No that's fine, it sets me apart from all the ppl with the same name :)

brb having a child and naming them "bartjanssens92" with no last name.

Merged, thanks and welcome to the project!! \o/

Now you gotta get some real code in, so that people know you're a serious hacker too! (Happy to mentor if you'd like a push or help finding something to work on.)

PS: It's cool that you used GIMP.

**Pull request merged**
