### PR TITLE
test: Fix broken gometalinter test

### PR DESCRIPTION
**Pull request by purpleidea**
The test for gometalinter got silently broken in an earlier commit.
Look for the missing space that was added back in this commit to see
why! In any case, this now fixes some of the things that weren't
previously caught by this change.

If anyone knows how to run these sorts of tests properly so that entire
packages are tested and so that we can enable additional tests, please
let me know!

It's also unclear why goreportcard catches a few additional problems
which aren't found by running this ourselves.

See:
https://goreportcard.com/report/github.com/purpleidea/mgmt
for more information.

### CODE REVIEW

**Comment by purpleidea** [comment]
/cc @jonathangold ;)

See if you can spot the bug here: https://github.com/purpleidea/mgmt/commit/62ca1260#diff-b16d54e137a1454f5f9cfc199e89de04R46

**Comment by jonathangold** [comment]
@purpleidea I see. Had to exclude the bindata dir from headerfmt. Makes sense.

**Comment by jonathangold** [comment]
Forgot the space. :( My bad.

**Comment by purpleidea** [comment]
@jonathangold No, look again...

**Comment by purpleidea** [comment]
Yeah! the space :)

**Comment by purpleidea** [comment]
Anyways! We all make bugs. Especially me!

**Pull request merged**
