### PR TITLE
docs: Change go required version to 1.8

### PR DESCRIPTION
**Pull request by juanluisvaladas**

### CODE REVIEW

**Comment by purpleidea** [comment]
@juanluisvaladas LGTM, but I think ci will fail because the word "change" would need to be capitalized.

Care to rebase and re-submit?

Thanks!

**Comment by purpleidea** [comment]
Yep: https://travis-ci.org/purpleidea/mgmt/jobs/270594266#L816

**Comment by juanluisvaladas** [comment]
It should be working now. I misunderstood how the test script worked.
Thanks

**Comment by purpleidea** [comment]
@juanluisvaladas Thanks! LGTM, just waiting for CI...

**Comment by purpleidea** [comment]
Merged :) Congrats on first patch, hope to see more.

**Pull request merged**
