### PR TITLE
lang: add debug flag and Logf to fact init struct

### PR DESCRIPTION
**Pull request by keur**

### CODE REVIEW

**Comment by keur** [comment]
@purpleidea sorry :p. fixed and force-pushed.

**Comment by purpleidea** [comment]
No sorry needed :)

**Comment by purpleidea** [comment]
LGTM :) Will merge shortly.

**Comment by purpleidea** [comment]
Merged in 34550246f497f252c1d7b1d505d0ce7fe7afc7bc

Thanks and sorry for the delay!

**Pull request closed without merging**
