### PR TITLE
build: Add rubygems to make deps target

### PR DESCRIPTION
**Pull request by jonathangold**

### CODE REVIEW

**Comment by purpleidea** [comment]
Sweet... What's this for?

**Comment by jonathangold** [comment]
Can't do:
https://github.com/purpleidea/mgmt/blob/f342e06ef0d0fc173dcb5320e9a376f14d561868/misc/make-deps.sh#L103
without rubygems

**Comment by purpleidea** [comment]
Sweet, good catch. Do you mind adding a small comment to the commit
message so people like me aren't confused in the future?

**Comment by jonathangold** [comment]
@purpleidea done

**Comment by purpleidea** [comment]
LGTM =D

**Pull request merged**
