### PR TITLE
lang: funcs: Add strings.split function

### PR DESCRIPTION
**Pull request by landervdb**
Signed-off-by: Lander Van den Bulcke <landervdb@inuits.eu>

### CODE REVIEW

**Comment by purpleidea** [comment]
LGTM :) Thanks!

**Comment by purpleidea** [comment]
Would you like to rebase to current git master so as to preserve your sig, or should I rebase and merge as-is?

**Comment by landervdb** [comment]
Rebased :)

**Comment by purpleidea** [comment]
On Thu, Feb 7, 2019 at 4:57 AM Lander Van den Bulcke
<notifications@github.com> wrote:
>
> Rebased :)

Merged, thank you!

**Pull request merged**
