### PR TITLE
docs: Fix link

### PR DESCRIPTION
**Pull request by schu**

### CODE REVIEW

**Comment by purpleidea** [comment]
Patch LGTM, thanks!

In case you're in the mood, here's a related open issue we didn't get to you:

https://github.com/purpleidea/mgmt/issues/440

**Comment by purpleidea** [comment]
PS: Did you mean to send this commit instead? https://github.com/kinvolk/mgmt/commit/50bbd4ebe3357ab6ead31a8d560013ff7685d5a1

**Comment by schu** [comment]
> PS: Did you mean to send this commit instead? kinvolk@50bbd4e

:) I changed the other link blindly but then noticed that there is no file `docker-guide.md` in the docs directory. So no.

**Comment by purpleidea** [comment]
Anything matching `*docker*` has possibly rotted, because I don't really use it.

**Comment by purpleidea** [comment]
Merged, thanks! If you'd like something more fun to work on, or if you're learning golang or mgmt and want some guidance, please let us know!

**Pull request merged**
