### PR TITLE
doc: Fix link to puppet guide

### PR DESCRIPTION
**Pull request by cure**

### CODE REVIEW

**Comment by purpleidea** [comment]
@cure Thanks for the patch... Please have a look at:

https://github.com/purpleidea/mgmt/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Commit message fails test.

**Comment by purpleidea** [comment]
Hey @cure are you going to fixup the commit message so it passes tests, or should I close? Thanks!

**Comment by cure** [comment]
@purpleidea thanks for the reminder, all green now!

**Comment by purpleidea** [comment]
LGTM, thanks for the patch!

**Comment by purpleidea** [comment]
Rebased to master and merged, thanks!

**Pull request closed without merging**
